[package]
name = "tinymd"
version = "0.1.0"
description = "A useless markdown compiler, for the love of compilers!"
authors = ["ProCode2 <bpro249@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
